name: fluttermipush
description: Flutter 小米推送
version: 0.1.1
author: Scott Wang
homepage: 

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.xiaomi.mipush
        pluginClass: FlutterXiaomiMipushPlugin
      ios:
        pluginClass: FlutterXiaomiMipushPlugin